"""Optimize prompts for lm-eval harness evaluations."""

from __future__ import annotations

from typing import Any

import lm_eval

from llm_optimizer.tasks.base_task import Task


class PromptOptimization(Task):
    """Prompt optimization 'task'."""

    def __init__(
        self,
        metric: str = 'f1',
        direction: str = 'maximize',
        **kwargs: Any,
    ) -> None:
        """Initialize task."""
        task_metric_dict = {'drop': 'f1'}
        self.benchmark = kwargs['benchmark']
        if self.benchmark not in task_metric_dict:
            raise KeyError(
                f'{self.benchmark} not supported yet. '
                'consider adding it to the task',
            )
        self.model_name = kwargs['model_name']
        self.task_description = (
            f'Craft a prompt prefix to boost a downstream '
            f"{self.model_name}'s score on the {self.benchmark} benchmark."
        )

        self.solution_description = 'prompt prefix'
        self.metric = task_metric_dict['f1']
        self.direction = direction
        self.seed_candidate = 'placeholder prompt prefix'
        self.eval_model_gpu_id = kwargs['eval_model_gpu_id']

        self.device = 'cpu'
        if self.eval_model_gpu_id != 'cpu':
            self.device = f'cuda:{self.eval_model_gpu_id}'

    def evaluate(self, solution: str) -> tuple[float, dict[str, Any]]:
        """Evaluate LLM optimized solution."""
        # Pass the native 'drop' task directly
        raw_results = lm_eval.simple_evaluate(
            model='hf',
            model_args=(
                f'pretrained={self.model_name},'
                f'trust_remote_code=True,'
                f'attn_implementation=sdpa'
            ),
            tasks=[
                self.benchmark,
            ],  # Use the official registered dataset string
            num_fewshot=0,  # 0-shot optimizes speed significantly
            batch_size='auto',
            device=self.device,
            limit=50,  # Artificially limit prompts for quick testing
            system_instruction=solution,  # Forces prefix before generation
            apply_chat_template=True,  # Properly wraps the prompt
        )

        # 1. Print the clean summary table generated by the harness
        print(lm_eval.utils.make_table(raw_results))

        # 2. Extract metrics safely using the standard native keys
        drop_metrics = raw_results['results'][self.benchmark]
        score = drop_metrics[f'{self.metric},none']

        print(f'{self.metric} Score:        {score:.4f}')

        # NOTE(MS): this won't have meta-data
        return score, {}
