"""Logic to abstract away LLM-driven optimization via ShinkaEvolve."""

from __future__ import annotations

import asyncio
import json
import os
from typing import Any

import shinka.core.async_runner as _shinka_async_runner
import shinka.database.dbase as _shinka_dbase
import shinka.llm.llm as _shinka_llm
from sentence_transformers import SentenceTransformer
from shinka.core import EvolutionConfig
from shinka.core import ShinkaEvolveRunner
from shinka.database import DatabaseConfig
from shinka.database import ProgramDatabase
from shinka.embed.embedding import EmbeddingClient as _ShinkaEmbeddingClient
from shinka.launch import LocalJobConfig
from shinka.local_openai_config import parse_local_openai_model

from llm_optimizer.optimizers.base_optimizer import Optimizer
from llm_optimizer.optimizers.opro import QUERY_PREFIXES
from llm_optimizer.optimizers.opro import SolutionBank
from llm_optimizer.tasks.base_task import Task

# NOTE(MS): fixed, task-agnostic -- rebuilds the Task from task_spec.json
# on every call, since each candidate is evaluated in a fresh subprocess
# with no memory shared with the optimizer process.
_EVALUATE_TEMPLATE = '''"""Auto-generated by ShinkaEvolveOptimizer."""
import argparse
import importlib
import json
import re

parser = argparse.ArgumentParser()
parser.add_argument('--program_path', required=True)
parser.add_argument('--results_dir', required=True)
parser.add_argument('--task_spec', required=True)
args = parser.parse_args()

with open(args.task_spec, encoding='utf-8') as f:
    spec = json.load(f)

module = importlib.import_module(spec['task_module'])
task = getattr(module, spec['task_class'])(**spec['task_kwargs'])

with open(args.program_path, encoding='utf-8') as f:
    solution = f.read()

# same EVOLVE-BLOCK extraction as open_evolve.py's evaluator()
match = re.search(
    r'#\\s*EVOLVE-BLOCK-START\\s*\\n(.*?)\\n\\s*#\\s*EVOLVE-BLOCK-END',
    solution,
    re.DOTALL,
)
solution = match.group(1).strip() if match else solution.strip()

try:
    score, extra_info, _val_score = task.evaluate(solution)
    error = None
except Exception as exc:  # noqa: BLE001 -- must report, not crash the run
    score = getattr(task, 'failed_score', 0.0) or 0.0
    extra_info = {}
    error = repr(exc)

metrics = {'combined_score': score, 'public': extra_info}
with open(f'{args.results_dir}/metrics.json', 'w', encoding='utf-8') as f:
    json.dump(metrics, f, default=str)
with open(f'{args.results_dir}/correct.json', 'w', encoding='utf-8') as f:
    json.dump({'correct': error is None, 'error': error}, f)
'''

# NOTE(MS): env var our own process sets so shinka's local/ model
# convention can read the api key back out of it (see optimize()).
_API_KEY_ENV_VAR = 'SHINKA_LOCAL_API_KEY'
_JUDGE_API_KEY_ENV_VAR = 'SHINKA_LOCAL_JUDGE_API_KEY'
# ours defaults sim_thresh to 0 (off); shinka's novelty judge defaults its
# own cosine threshold to 0.99 -- tighten it to a more useful default.
_DEFAULT_CODE_EMBED_SIM_THRESHOLD = 0.95

# chunk size (generations) for incremental checkpointing/max_tokens checks.
_CHECKPOINT_INTERVAL_GENERATIONS = 10


class _LocalSentenceTransformerEmbeddingClient(_ShinkaEmbeddingClient):
    """Drop-in replacement for shinka's EmbeddingClient/AsyncEmbeddingClient.

    Backed by the same in-process, CPU sentence-transformers models OPRO's
    own diversity check uses, instead of shinka's OpenAI/Azure/Google/
    OpenRouter/local-HTTP embedding providers, which require either a
    paid API or a separately-hosted /v1/embeddings server.

    Duck-typed against both call sites shinka actually exercises:
      - shinka.core.async_runner: AsyncEmbeddingClient(model_name=...),
        then .embed_async(code) -> (embedding, cost)
      - shinka.database.dbase: EmbeddingClient(model_name=...), then
        .get_embedding(code) -> (embedding, cost), plus the inherited
        get_embedding_clusters/get_dim_reduction (only operate on
        already-computed vectors, so need no override).

    Installed via _patch_shinka_embedding_clients() -- shinka builds these
    clients itself from a bare model-name string with no injection point
    in EvolutionConfig/DatabaseConfig, so this replaces the module-global
    class references shinka resolves them from instead.

    model_name arrives disguised as shinka's own 'local/<model>@<url>'
    convention (built in optimize() below) -- ShinkaEvolveRunner.__init__
    validates evo_config.embedding_model against shinka's known naming
    conventions (resolve_embedding_backend) *before* this class is ever
    constructed, independently of the monkeypatch below, so a bare
    sentence-transformers name like 'nomic-ai/CodeRankEmbed' fails that
    check with ValueError even though this class never uses the URL.
    Unwrapped back to the real model name here via the same
    parse_local_openai_model shinka itself uses for its local/ LLM models.
    """

    def __init__(self, model_name: str, verbose: bool = False) -> None:
        local_match = parse_local_openai_model(model_name)
        self.model_name = (
            local_match.api_model_name if local_match else model_name
        )
        self.provider = 'sentence_transformers'
        self.verbose = verbose
        # same construction as SolutionBank's diversity check (opro.py) --
        # CPU, trust_remote_code=True for nomic-ai/CodeRankEmbed's custom
        # modeling code (harmless no-op for all-MiniLM-L6-v2's stock arch)
        self._model = SentenceTransformer(
            self.model_name,
            device='cpu',
            trust_remote_code=True,
        )

    def get_embedding(
        self,
        code: str | list[str],
    ) -> tuple[list[float], float] | tuple[list[list[float]], float]:
        """Sync embed; local inference has no API cost, so cost is always 0."""
        single = isinstance(code, str)
        texts: list[str] = [code] if isinstance(code, str) else list(code)
        # NOTE(MS): matches opro.py's QUERY_PREFIXES convention -- shinka
        # calls this once per program with no query/document distinction
        # (each candidate is "is this similar to anything else"), so the
        # prefix applies to every text embedded here.
        prefix = QUERY_PREFIXES.get(self.model_name, '')
        vecs = self._model.encode(
            [prefix + t for t in texts],
            convert_to_numpy=True,
        ).tolist()
        return (vecs[0], 0.0) if single else (vecs, 0.0)

    async def embed_async(
        self,
        code: str | list[str],
    ) -> tuple[list[float], float] | tuple[list[list[float]], float]:
        """Async embed.

        SentenceTransformer has no async API -- offload to a thread, same
        pattern shinka's own AsyncEmbeddingClient uses for Gemini.
        """
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, self.get_embedding, code)


_shinka_embedding_clients_patched = False


def _patch_shinka_embedding_clients() -> None:
    """Point shinka's embedding-client factories at our local subclass.

    Idempotent and process-global: shinka resolves these from its own
    module globals with no config-level way to inject an instance, so
    this patches those names once per process rather than per-run.
    """
    global _shinka_embedding_clients_patched  # noqa: PLW0603
    if _shinka_embedding_clients_patched:
        return
    _shinka_async_runner.AsyncEmbeddingClient = (
        _LocalSentenceTransformerEmbeddingClient
    )
    _shinka_dbase.EmbeddingClient = _LocalSentenceTransformerEmbeddingClient
    _shinka_embedding_clients_patched = True


# Chronological, this-process-only log of every shinka LLM call's tokens:
# proposal, novelty judge, meta-summarizer.
_query_token_log: list[dict[str, int]] = []
_shinka_query_metering_patched = False


def _patch_shinka_query_metering() -> None:
    """Log every shinka LLM call's tokens to _query_token_log.

    Catches novelty-judge and rejected/resampled proposal calls, which
    shinka itself never persists to a Program (see _populate_solution_bank).
    """
    global _shinka_query_metering_patched  # noqa: PLW0603
    if _shinka_query_metering_patched:
        return
    original_query_async = _shinka_llm.query_async

    async def _metered_query_async(*args: Any, **kwargs: Any) -> Any:
        result = await original_query_async(*args, **kwargs)
        if result is not None:
            _query_token_log.append(
                {
                    'input_tokens': getattr(result, 'input_tokens', 0) or 0,
                    'output_tokens': getattr(result, 'output_tokens', 0) or 0,
                    'thinking_tokens': getattr(result, 'thinking_tokens', 0)
                    or 0,
                },
            )
        return result

    _shinka_llm.query_async = _metered_query_async
    _shinka_query_metering_patched = True


class ShinkaEvolveOptimizer(Optimizer):
    """LLM optimizer via ShinkaEvolve.

    # https://github.com/SakanaAI/ShinkaEvolve
    state includes: task, solution_score pairs, stopping criteria
    """

    def __init__(
        self,
        task: Task,
        noise: bool = False,
        num_past_sol: int = 5,
        num_parallel_search: int = 1,
        **kwargs: Any,
    ) -> None:
        """Init optimizer."""
        self.task = task
        self.experiment_dir = f'{kwargs["experiment_dir"]}/'
        os.makedirs(self.experiment_dir, exist_ok=True)

        # reporting/observability side-channel only, same as open_evolve.py
        self.solution_bank = SolutionBank(
            seed=kwargs['seed'],
            max_population_size=kwargs['max_population_size'],
            pruning_strategy=kwargs['pruning_strategy'],
            failed_score=getattr(task, 'failed_score', None),
        )
        self.solution_bank.read_from_checkpoint(self.experiment_dir)

        self.init_population_path = kwargs['init_population_path']
        already_seeded = bool(self.solution_bank.never_prune_bank)
        if os.path.isfile(self.init_population_path):
            with open(self.init_population_path, encoding='utf-8') as f:
                population = json.load(f)
            self.task.seed_candidate = max(
                population.values(),
                key=lambda e: e['score'],
            )['solution']
            if not already_seeded:
                self.solution_bank.cumulative_tokens_spent += max(
                    e.get('cumulative_tokens_spent', 0)
                    for e in population.values()
                )
        # _query_token_log position consumed; see _populate_solution_bank.
        self._token_log_idx = 0

        self.task_kwargs = kwargs['task_kwargs']
        self.model_name = kwargs['model_name']
        self.base_url = kwargs['base_url']
        self.api_key = kwargs['api_key']
        if self.api_key is None:
            raise ValueError('API key not found.')

        # our diversity-check knobs (OPRO) mapped onto shinka's own
        # novelty judge, since it has no other consumer here
        self.llm_judge = kwargs.get('llm_judge')
        self.llm_judge_base_url = kwargs.get('llm_judge_base_url')
        self.llm_judge_api_key = kwargs.get('llm_judge_api_key')
        self.embed_model_name = kwargs.get('embed_model')
        # OPRO's --sim_thresh default (0.0) means "off"; shinka has no
        # off state for its own cosine gate, so 0.0 falls back to the
        # tighter _DEFAULT_CODE_EMBED_SIM_THRESHOLD instead of 0.0 (which
        # would flag every candidate as too similar).
        self.code_embed_sim_threshold = (
            kwargs.get('sim_thresh') or _DEFAULT_CODE_EMBED_SIM_THRESHOLD
        )

        self.n = num_past_sol
        self.noise = noise
        self.num_parallel_search = num_parallel_search

    def _write_task_spec(self) -> str:
        """Serialize (task_module, task_class, task_kwargs) for evaluate.py."""
        spec = {
            'task_module': type(self.task).__module__,
            'task_class': type(self.task).__qualname__,
            'task_kwargs': self.task_kwargs,
        }
        spec_path = os.path.join(self.experiment_dir, 'task_spec.json')
        with open(spec_path, 'w', encoding='utf-8') as f:
            json.dump(spec, f)
        return spec_path

    def _wrapped_seed_candidate(self) -> str:
        """Ensure the seed candidate has an EVOLVE-BLOCK region.

        shinka's full-patch application hard-requires at least one
        EVOLVE-BLOCK region in the *original* program -- unlike
        OpenEvolve's full-rewrite mode, there's no whole-file fallback.
        None of this repo's task seed_candidates include the markers, so
        wrap the whole thing as one mutable region when they're missing.
        """
        seed = self.task.seed_candidate
        if 'EVOLVE-BLOCK-START' in seed:
            return seed
        return f'# EVOLVE-BLOCK-START\n{seed}\n# EVOLVE-BLOCK-END'

    def _populate_solution_bank(self) -> None:
        """Extend SolutionBank with any db programs not already in it.

        Incremental, not a rebuild: already-checkpointed entries (loaded by
        read_from_checkpoint, possibly written by an earlier process) keep
        their original cumulative_tokens_spent and are never recomputed --
        only new programs beyond len(never_prune_bank) get appended.
        """
        db_path = os.path.join(self.experiment_dir, 'programs.sqlite')
        if not os.path.exists(db_path):
            return
        db = ProgramDatabase(
            config=DatabaseConfig(db_path=db_path),
            read_only=True,
        )
        programs = sorted(db.get_all_programs(), key=lambda p: p.generation)
        db.close()

        already_added = len(self.solution_bank.never_prune_bank)
        for program in programs[already_added:]:
            llm_result = (program.metadata or {}).get('llm_result') or {}
            own_tokens = (
                llm_result.get('input_tokens', 0),
                llm_result.get('output_tokens', 0),
                llm_result.get('thinking_tokens', 0),
            )
            pending = 0
            # island-seeded copies of the initial program were never an
            # LLM call, so they have no entry in _query_token_log to
            # search for -- skip them rather than scanning the whole log
            # for a match that can't exist and consuming every real
            # program's entries along the way.
            if llm_result:
                matched = False
                while self._token_log_idx < len(_query_token_log):
                    entry = _query_token_log[self._token_log_idx]
                    self._token_log_idx += 1
                    entry_tokens = (
                        entry['input_tokens'],
                        entry['output_tokens'],
                        entry['thinking_tokens'],
                    )
                    pending += sum(entry_tokens)
                    if entry_tokens == own_tokens:
                        matched = True
                        break
                # no live log to correlate against (e.g. a resumed run,
                # fresh process) -- fall back to this program's own
                # tokens only.
                if not matched:
                    pending = sum(own_tokens)

            generation_metadata = {
                'input_tokens': llm_result.get('input_tokens', 0),
                'output_tokens': llm_result.get('output_tokens', 0),
                'reasoning_tokens': llm_result.get('thinking_tokens', 0),
                'total_tokens': pending,
            }
            self.solution_bank.add_solution_score_pair(
                program.code,
                program.combined_score,
                program.public_metrics,
                None,
                generation_metadata,
            )
            self.solution_bank.prune_population()
        self.solution_bank.save_to_json(self.experiment_dir)

    def optimize(
        self,
        num_iter: int = 5,
        max_tokens: int | None = None,
    ) -> None:
        """Optimization loop for task.

        max_tokens: optional cumulative token budget, checked every
            _CHECKPOINT_INTERVAL_GENERATIONS generations; None disables it.
        """
        os.environ[_API_KEY_ENV_VAR] = self.api_key
        spec_path = self._write_task_spec()
        # scoped to this call -- see _patch_shinka_query_metering().
        _query_token_log.clear()
        self._token_log_idx = 0
        _patch_shinka_query_metering()

        # None (default) disables the judge, same convention as OPRO.
        # embedding_model only feeds shinka's code_embed_sim_threshold
        # gate below, which only fires when novelty_llm_models is set --
        # so both are gated on llm_judge together, same as OPRO's
        # sim_thresh > 0 lazily loading its own embedding_model.
        novelty_llm_models = None
        embedding_model = None
        if self.llm_judge is not None:
            if self.llm_judge_api_key is None:
                raise ValueError('llm_judge API key not found.')
            os.environ[_JUDGE_API_KEY_ENV_VAR] = self.llm_judge_api_key
            novelty_llm_models = [
                f'local/{self.llm_judge}@{self.llm_judge_base_url}'
                f'?api_key_env={_JUDGE_API_KEY_ENV_VAR}',
            ]
            # disguised as shinka's local/<model>@<url> convention purely
            # to pass ShinkaEvolveRunner's upfront naming-convention
            # validation (see _LocalSentenceTransformerEmbeddingClient's
            # docstring) -- the URL is never actually dialed, since the
            # patched client bypasses shinka's HTTP/provider resolution
            # entirely and unwraps the real model name from this string.
            embedding_model = (
                f'local/{self.embed_model_name}@http://localhost/v1'
            )
            _patch_shinka_embedding_clients()

        task_sys_msg = (
            f'{self.task.task_description} '
            f'Your goal is to {self.task.direction} {self.task.metric}. '
            f'Output only the bare minimum text to reach the objective goal.'
        )
        evo_config = EvolutionConfig(
            task_sys_msg=task_sys_msg,
            num_generations=0,
            results_dir=self.experiment_dir,
            llm_models=[
                f'local/{self.model_name}@{self.base_url}'
                f'?api_key_env={_API_KEY_ENV_VAR}',
            ],
            # full-file rewrites only, to match GEPA/open_evolve's interface
            patch_types=['full'],
            patch_type_probs=[1.0],
            novelty_llm_models=novelty_llm_models,
            code_embed_sim_threshold=self.code_embed_sim_threshold,
            # in-process sentence-transformers model (see
            # _LocalSentenceTransformerEmbeddingClient), not shinka's
            # OpenAI-embedding default -- avoids a hard crash on a missing
            # OPENAI_API_KEY and matches OPRO's diversity-check model
            embedding_model=embedding_model,
        )
        db_config = DatabaseConfig(archive_size=self.n)
        job_config = LocalJobConfig(extra_cmd_args={'task_spec': spec_path})

        completed_target = 0
        while completed_target < num_iter:
            completed_target = min(
                completed_target + _CHECKPOINT_INTERVAL_GENERATIONS,
                num_iter,
            )
            evo_config.num_generations = completed_target
            runner = ShinkaEvolveRunner(
                evo_config=evo_config,
                job_config=job_config,
                db_config=db_config,
                # SolutionBank rebuild below assumes strictly sequential evals
                max_evaluation_jobs=1,
                max_proposal_jobs=self.num_parallel_search,
                init_program_str=self._wrapped_seed_candidate(),
                evaluate_str=_EVALUATE_TEMPLATE,
            )
            runner.run()
            self._populate_solution_bank()
            if (
                max_tokens is not None
                and self.solution_bank.get_cumulative_tokens_spent()
                >= max_tokens
            ):
                break
