"""Logic to abstract away LLM-driven optimization via ShinkaEvolve."""

from __future__ import annotations

import json
import os
from typing import Any

from shinka.core import EvolutionConfig
from shinka.core import ShinkaEvolveRunner
from shinka.database import DatabaseConfig
from shinka.database import ProgramDatabase
from shinka.launch import LocalJobConfig

from llm_optimizer.optimizers.base_optimizer import Optimizer
from llm_optimizer.optimizers.opro import SolutionBank
from llm_optimizer.tasks.base_task import Task

# NOTE(MS): fixed, task-agnostic -- rebuilds the Task from task_spec.json
# on every call, since each candidate is evaluated in a fresh subprocess
# with no memory shared with the optimizer process. See
# experiments/SHINKAEVOLVE_INTEGRATION_PLAN.md for why.
_EVALUATE_TEMPLATE = '''"""Auto-generated by ShinkaEvolveOptimizer."""
import argparse
import importlib
import json
import re

parser = argparse.ArgumentParser()
parser.add_argument('--program_path', required=True)
parser.add_argument('--results_dir', required=True)
parser.add_argument('--task_spec', required=True)
args = parser.parse_args()

with open(args.task_spec, encoding='utf-8') as f:
    spec = json.load(f)

module = importlib.import_module(spec['task_module'])
task = getattr(module, spec['task_class'])(**spec['task_kwargs'])

with open(args.program_path, encoding='utf-8') as f:
    solution = f.read()

# same EVOLVE-BLOCK extraction as open_evolve.py's evaluator()
match = re.search(
    r'#\\s*EVOLVE-BLOCK-START\\s*\\n(.*?)\\n\\s*#\\s*EVOLVE-BLOCK-END',
    solution,
    re.DOTALL,
)
solution = match.group(1).strip() if match else solution.strip()

try:
    score, extra_info, _val_score = task.evaluate(solution)
    error = None
except Exception as exc:  # noqa: BLE001 -- must report, not crash the run
    score = getattr(task, 'failed_score', 0.0) or 0.0
    extra_info = {}
    error = repr(exc)

metrics = {'combined_score': score, 'public': extra_info}
with open(f'{args.results_dir}/metrics.json', 'w', encoding='utf-8') as f:
    json.dump(metrics, f, default=str)
with open(f'{args.results_dir}/correct.json', 'w', encoding='utf-8') as f:
    json.dump({'correct': error is None, 'error': error}, f)
'''

# NOTE(MS): env var our own process sets so shinka's local/ model
# convention can read the api key back out of it (see optimize()).
_API_KEY_ENV_VAR = 'SHINKA_LOCAL_API_KEY'
_JUDGE_API_KEY_ENV_VAR = 'SHINKA_LOCAL_JUDGE_API_KEY'
# ours defaults sim_thresh to 0 (off); shinka's novelty judge defaults its
# own cosine threshold to 0.99 -- tighten it to a more useful default.
_DEFAULT_CODE_EMBED_SIM_THRESHOLD = 0.95


class ShinkaEvolveOptimizer(Optimizer):
    """LLM optimizer via ShinkaEvolve.

    # https://github.com/SakanaAI/ShinkaEvolve
    state includes: task, solution_score pairs, stopping criteria
    """

    def __init__(
        self,
        task: Task,
        noise: bool = False,
        num_past_sol: int = 5,
        num_parallel_search: int = 1,
        **kwargs: Any,
    ) -> None:
        """Init optimizer."""
        self.task = task
        self.experiment_dir = f'{kwargs["experiment_dir"]}/'
        os.makedirs(self.experiment_dir, exist_ok=True)

        # reporting/observability side-channel only, same as open_evolve.py
        self.solution_bank = SolutionBank(
            seed=kwargs['seed'],
            max_population_size=kwargs['max_population_size'],
            pruning_strategy=kwargs['pruning_strategy'],
            failed_score=getattr(task, 'failed_score', None),
        )
        self.solution_bank.read_from_checkpoint(self.experiment_dir)

        self.task_kwargs = kwargs['task_kwargs']
        self.model_name = kwargs['model_name']
        self.base_url = kwargs['base_url']
        self.api_key = kwargs['api_key']
        if self.api_key is None:
            raise ValueError('API key not found.')

        # our diversity-check knob (OPRO) mapped onto shinka's own
        # novelty judge, since it has no other consumer here
        self.llm_judge = kwargs.get('llm_judge')
        self.llm_judge_base_url = kwargs.get('llm_judge_base_url')
        self.llm_judge_api_key = kwargs.get('llm_judge_api_key')

        self.n = num_past_sol
        self.noise = noise
        self.num_parallel_search = num_parallel_search

    def _write_task_spec(self) -> str:
        """Serialize (task_module, task_class, task_kwargs) for evaluate.py."""
        spec = {
            'task_module': type(self.task).__module__,
            'task_class': type(self.task).__qualname__,
            'task_kwargs': self.task_kwargs,
        }
        spec_path = os.path.join(self.experiment_dir, 'task_spec.json')
        with open(spec_path, 'w', encoding='utf-8') as f:
            json.dump(spec, f)
        return spec_path

    def _populate_solution_bank(self) -> None:
        """Rebuild SolutionBank from ShinkaEvolve's own persisted db.

        Full rebuild (not incremental) -- idempotent across resumes, and
        sidesteps needing to track which programs were already added.
        """
        db_path = os.path.join(self.experiment_dir, 'programs.sqlite')
        if not os.path.exists(db_path):
            return
        db = ProgramDatabase(
            config=DatabaseConfig(db_path=db_path),
            read_only=True,
        )
        programs = sorted(db.get_all_programs(), key=lambda p: p.generation)
        db.close()

        bank = SolutionBank(
            seed=self.solution_bank.seed,
            max_population_size=self.solution_bank.max_population_size,
            pruning_strategy=self.solution_bank.pruning_strategy,
            failed_score=self.solution_bank.failed_score,
        )
        for program in programs:
            llm_result = (program.metadata or {}).get('llm_result') or {}
            generation_metadata = {
                'input_tokens': llm_result.get('input_tokens', 0),
                'output_tokens': llm_result.get('output_tokens', 0),
                'reasoning_tokens': llm_result.get('thinking_tokens', 0),
                'total_tokens': (
                    llm_result.get('input_tokens', 0)
                    + llm_result.get('output_tokens', 0)
                    + llm_result.get('thinking_tokens', 0)
                ),
            }
            bank.add_solution_score_pair(
                program.code,
                program.combined_score,
                program.public_metrics,
                None,
                generation_metadata,
            )
            bank.prune_population()
        self.solution_bank = bank
        self.solution_bank.save_to_json(self.experiment_dir)

    def optimize(self, num_iter: int = 5) -> None:
        """Optimization loop for task."""
        os.environ[_API_KEY_ENV_VAR] = self.api_key
        spec_path = self._write_task_spec()

        # None (default) disables the judge, same convention as OPRO
        novelty_llm_models = None
        if self.llm_judge is not None:
            if self.llm_judge_api_key is None:
                raise ValueError('llm_judge API key not found.')
            os.environ[_JUDGE_API_KEY_ENV_VAR] = self.llm_judge_api_key
            novelty_llm_models = [
                f'local/{self.llm_judge}@{self.llm_judge_base_url}'
                f'?api_key_env={_JUDGE_API_KEY_ENV_VAR}',
            ]

        task_sys_msg = (
            f'{self.task.task_description} '
            f'Your goal is to {self.task.direction} {self.task.metric}. '
            f'Output only the bare minimum text to reach the objective goal.'
        )
        evo_config = EvolutionConfig(
            task_sys_msg=task_sys_msg,
            num_generations=num_iter,
            results_dir=self.experiment_dir,
            llm_models=[
                f'local/{self.model_name}@{self.base_url}'
                f'?api_key_env={_API_KEY_ENV_VAR}',
            ],
            # full-file rewrites only, to match GEPA/open_evolve's interface
            patch_types=['full'],
            patch_type_probs=[1.0],
            novelty_llm_models=novelty_llm_models,
            code_embed_sim_threshold=_DEFAULT_CODE_EMBED_SIM_THRESHOLD,
            # no local/ embedding model wired up -- avoid a hard crash on a
            # missing OPENAI_API_KEY for shinka's OpenAI-embedding default
            embedding_model=None,
        )
        db_config = DatabaseConfig(archive_size=self.n)
        job_config = LocalJobConfig(extra_cmd_args={'task_spec': spec_path})

        runner = ShinkaEvolveRunner(
            evo_config=evo_config,
            job_config=job_config,
            db_config=db_config,
            # SolutionBank rebuild below assumes strictly sequential evals
            max_evaluation_jobs=1,
            max_proposal_jobs=self.num_parallel_search,
            init_program_str=self.task.seed_candidate,
            evaluate_str=_EVALUATE_TEMPLATE,
        )
        runner.run()

        self._populate_solution_bank()
